= User Authentication Authorization Service
:toc:

== Getting started 

=== Enable Authorization Server

	@SpringBootApplication
	@EnableAuthorizationServer

=== Application files

see `application.yml`, `schema.sql` and `data.sql` files
	
=== Before start project

IMPORTANT: keep pushing authDBXX version in `application.yml` or rename `data.sql` to `data.txt`
      
=== cURL test

*Grant Type: client_credentials*

	curl -s -X POST -u "app-mobile:app-mobile123" -d "grant_type=client_credentials" localhost:9191/oauth/token | pjson

*Grant Type: password*  

	curl -s -X POST -u 'app-mobile:app-mobile123' 'localhost:9191/oauth/token?grant_type=password&username=jane-doe&password=jane-doe123&scope=READ' | pjson

*Refresh Token*

	curl -X POST -u "app-mobile:app-mobile123" -d "grant_type=refresh_token&refresh_token=438fa86b-9174-4ae6-a8fe-faa9981955f3" http://localhost:9191/oauth/token

*Check Token*

	curl -s -u 'app-mobile:app-mobile123' 'localhost:9191/oauth/check_token?token=ecc66471-0508-4855-adf4-4238559b0921' | pjson
		